fail_fast: true

services:
  - docker

env:
  - IMAGE_NAME=mistermatt/blog

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $IMAGE_NAME .
  - docker push $IMAGE_NAME