source: src
destination: _site

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: Matthieu Vion

timezone: Europe/Paris

name: Blog de Matthieu
email: contact+blog@mvion.fr
author: Matthieu Vion
description: Notes d'un développeur ébahi.
url: https://blog.mvion.fr

social:
    twitter: https://twitter.com/Mistermatt007
    mastodon: https://mstdn.io/@Matthieu
    github: https://github.com/MattMattV
    email: contact+blog@mvion.fr
    keybase: https://keybase.io/mvion
    linkedin: https://www.linkedin.com/in/matthieu-vion/

seo:
    googleVerification: lza1DyoYYkqLvSUhc5Lsrc2IwOHOvZiCHqUk_qkIohc

sass:
    load_paths: ../node_modules/@ibm/plex/scss/

exclude:
  - node_modules
  - .gitignore
  - gulpfile.js
  - package.json
  - package-lock.json
  - Dockerfile
  - README.md